BEGIN TRANSACTION;

INSERT INTO "mip" VALUES('AerChemMIP','AerChemMIP','Aerosols and Chemistry Model Intercomparison Project',NULL,'https://wiki.met.no/aerocom/aerchemmip/start');
INSERT INTO "mip" VALUES('C4MIP','C4MIP','Coupled Climate Carbon Cycle Model Intercomparison Project',NULL,'http://www.c4mip.net');
INSERT INTO "mip" VALUES('CCMI','CCMI','Chemistry-Climate Model Initiative',NULL,'http://www.met.reading.ac.uk/ccmi/');
INSERT INTO "mip" VALUES('CDRMIP','CDRMIP','Carbon Dioxide Removal Model Intercomparison Project',NULL,'https://www.wcrp-climate.org/modelling-wgcm-mip-catalogue/cmip6-endorsed-mips-article/1302-modelling-cmip6-cdrrmip');
INSERT INTO "mip" VALUES('CFMIP','CFMIP','Cloud Feedback Model Intercomparison Project',NULL,'http://www.cfmip.net/');
INSERT INTO "mip" VALUES('CMIP','CMIP','Coupled Model Intercomparison Project',NULL,NULL);
INSERT INTO "mip" VALUES('CMIP5','CMIP5','Coupled Model Intercomparison Project, Phase 5',NULL,NULL);
INSERT INTO "mip" VALUES('CMIP6','CMIP6','Coupled Model Intercomparison Project, Phase 6',NULL,'http://www.wcrp-climate.org/wgcm-cmip/wgcm-cmip6');
INSERT INTO "mip" VALUES('CORDEX','CORDEX','Coordinated Regional Downscaling Experiment (CORDEX)',NULL,'https://www.wcrp-climate.org/modelling-wgcm-mip-catalogue/cmip6-endorsed-mips-article/1052-modelling-cmip6-cordex');
INSERT INTO "mip" VALUES('DAMIP','DAMIP','Detection and Attribution Model Intercomparison Project',NULL,'http://www.wcrp-climate.org/modelling-wgcm-mip-catalogue/modelling-wgcm-mips/475-modelling-wgcm-damip');
INSERT INTO "mip" VALUES('DCPP','DCPP','Decadal Climate Prediction Project',NULL,'https://www.wcrp-climate.org/dcp-overview');
INSERT INTO "mip" VALUES('DECK','DECK','DECK - set of standard CMIP runs',NULL,NULL);
INSERT INTO "mip" VALUES('DynVarMIP','DynVarMIP','Modelling the Dynamics and Variability of the Stratosphere-Troposphere System',NULL,'http://www.sparcdynvar.org/models-data/');
INSERT INTO "mip" VALUES('FAFMIP','FAFMIP','Flux-Anomaly-Forced Model Intercomparison Project',NULL,'http://www.fafmip.org');
INSERT INTO "mip" VALUES('GeoMIP','GeoMIP','Geoengineering Model Intercomparison Project',NULL,'http://climate.envsci.rutgers.edu/GeoMIP/index.html');
INSERT INTO "mip" VALUES('GMMIP','GMMIP','Global Monsoons Model Intercomparison Project',NULL,'http://www.met.reading.ac.uk/~sws05agt/MonsoonMIP/');
INSERT INTO "mip" VALUES('HighResMIP','HighResMIP','High Resolution Model Intercomparison Project',NULL,'http://collab.knmi.nl/project/highresmip/');
INSERT INTO "mip" VALUES('ISMIP6','ISMIP6','Ice Sheet Model Intercomparison Project for CMIP6',NULL,'http://www.climate-cryosphere.org/activities/targeted/ismip6');
INSERT INTO "mip" VALUES('LS3MIP','LS3MIP','Land Surface, Snow and Soil Moisture MIP',NULL,'http://www.climate-cryosphere.org/activities/targeted/ls3mip');
INSERT INTO "mip" VALUES('LUMIP','LUMIP','Land-Use Model Intercomparison Project',NULL,'https://cmip.ucar.edu/lumip');
INSERT INTO "mip" VALUES('OMIP','OMIP','Ocean Model Intercomparison Project',NULL,'https://www.wcrp-climate.org/modelling-wgcm-mip-catalogue/cmip6-endorsed-mips-article/1063-modelling-cmip6-omip');
INSERT INTO "mip" VALUES('PAMIP','PAMIP','Polar Amplificaton Model Intercomparison Project',NULL,'https://www.wcrp-climate.org/modelling-wgcm-mip-catalogue/cmip6-endorsed-mips-article/1303-modelling-cmip6-pamip');
INSERT INTO "mip" VALUES('PMIP','PMIP','Palaeoclimate Modelling Intercomparison Project',NULL,'https://pmip.lsce.ipsl.fr/');
INSERT INTO "mip" VALUES('RFMIP','RFMIP','Radiative Forcing Model Intercomparison Project',NULL,'https://rfmip.leeds.ac.uk/about-rfmip/');
INSERT INTO "mip" VALUES('ScenarioMIP','ScenarioMIP','Scenario Model Intercomparison Project',NULL,'https://cmip.ucar.edu/scenario-mip');
INSERT INTO "mip" VALUES('SIMIP','SIMIP','Sea Ice Model Intercomparison Project',NULL,'http://gaim.unh.edu/Structure/Future/MIPs/SIMIP.html');
INSERT INTO "mip" VALUES('SPECS','SPECS','Sesonal-to-decadal climate Prediction for the improvement of European Climate Services',NULL,'http://www.specs-fp7.eu/');
INSERT INTO "mip" VALUES('VIACSAB','VIACSAB','Vulnerability, Impacts, Adaptation, and Climate Services Advisory Board (VIACS AB)',NULL,'https://www.wcrp-climate.org/modelling-wgcm-mip-catalogue/cmip6-endorsed-mips-article/1067-modelling-cmip6-viacs');
INSERT INTO "mip" VALUES('VolMIP','VolMIP','Volcanic Forcings Model Intercomparison Project',NULL,'http://volmip.org/cmip6.html');

COMMIT TRANSACTION;
